In [4]:
# Reference: https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html

In [2]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
#numpy does auto casting (to float)
np.array([3.14, 1, 2, 3])

array([3.14, 1.  , 2.  , 3.  ])

In [3]:
# explicit casting can also be done
np.array([1,2,3], dtype='float')

array([1., 2., 3.])

In [5]:
#multi dimentional array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#some standard prebuilt arrays

In [6]:
#zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
#ones
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
#random
np.random.random((3,5))

array([[0.09164027, 0.76377756, 0.91780668, 0.09610944, 0.4645553 ],
       [0.86318629, 0.81265759, 0.8847329 , 0.96938165, 0.81698323],
       [0.81173675, 0.46279897, 0.99778543, 0.36301832, 0.1745575 ]])

In [11]:
#random int
np.random.randint(0, 10, (3,5))

array([[4, 0, 5, 2, 4],
       [6, 9, 3, 4, 8],
       [1, 9, 7, 0, 0]])

In [3]:
np.random.seed(0)  # seed for reproducibility

In [4]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [16]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [5]:
# Slicing
# x[start:stop:step]

In [7]:
x1[:5]  # first five elements

array([5, 0, 3, 3, 7])

In [8]:
x1[5:]  # elements after index 5

array([9])

In [9]:
x1[4:7]  # middle sub-array

array([7, 9])

In [10]:
x1[::-1]  # all elements, reversed

array([9, 7, 3, 3, 0, 5])

In [11]:
# Multi-dimentional

In [12]:
x2[:2, :3]  # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [13]:
print(x2[:, 0])  # first column of x2

[3 7 1]


In [14]:
print(x2[0, :])  # first row of x2

[3 5 2 4]


In [18]:
# Concatenate

In [19]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [20]:
# UFuncs to speed up arithmetic operations on array

In [21]:
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

('x     =', array([1, 2, 3]))
('x + 5 =', array([6, 7, 8]))
('x - 5 =', array([-4, -3, -2]))
('x * 2 =', array([2, 4, 6]))
('x / 2 =', array([0, 1, 1]))
('x // 2 =', array([0, 1, 1]))


In [22]:
-(0.5*x + 1) ** 2

array([-2.25, -4.  , -6.25])

In [23]:
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

('x     =', array([1, 2, 3]))
('e^x   =', array([ 2.71828183,  7.3890561 , 20.08553692]))
('2^x   =', array([2., 4., 8.]))
('3^x   =', array([ 3,  9, 27]))


In [24]:
# Specialized ufuncs

In [25]:
from scipy import special

In [26]:
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

('gamma(x)     =', array([1.0000e+00, 2.4000e+01, 3.6288e+05]))
('ln|gamma(x)| =', array([ 0.        ,  3.17805383, 12.80182748]))
('beta(x, 2)   =', array([0.5       , 0.03333333, 0.00909091]))


In [27]:
# Specifying output

In [29]:
#faster than y = np.multiply(x, 10)
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [31]:
big_array = np.random.rand(1000000)

In [32]:
#min max sum
print(big_array.min(), big_array.max(), big_array.sum())

(1.8636745751088313e-06, 0.9999994002429613, 500772.27727188385)


In [5]:
#Broadcasting in practice

In [6]:
X = np.random.random((10, 3))

In [7]:
X

array([[0.54142903, 0.02446452, 0.0555565 ],
       [0.81663853, 0.528986  , 0.49431074],
       [0.17510304, 0.48651272, 0.65473788],
       [0.55873463, 0.32242747, 0.2976255 ],
       [0.78721988, 0.74556534, 0.20870959],
       [0.78011412, 0.93781098, 0.01986852],
       [0.16140033, 0.74405569, 0.68743887],
       [0.24066717, 0.19208606, 0.4410625 ],
       [0.96212293, 0.41073379, 0.36158993],
       [0.00096777, 0.11826457, 0.02655491]])

In [8]:
Xmean = X.mean(0)
Xmean

array([0.50243974, 0.45109071, 0.32474549])

In [10]:
X_centered = X - Xmean
X_centered

array([[ 0.03898929, -0.42662619, -0.26918899],
       [ 0.31419879,  0.07789529,  0.16956524],
       [-0.3273367 ,  0.03542201,  0.32999239],
       [ 0.05629488, -0.12866324, -0.02711999],
       [ 0.28478013,  0.29447462, -0.1160359 ],
       [ 0.27767438,  0.48672027, -0.30487698],
       [-0.34103941,  0.29296497,  0.36269338],
       [-0.26177258, -0.25900465,  0.11631701],
       [ 0.45968319, -0.04035692,  0.03684444],
       [-0.50147197, -0.33282615, -0.29819059]])

In [12]:
# Above operations enabled us to make means almost 0
X_centered.mean(0)

array([ 3.33066907e-17, -3.33066907e-17,  0.00000000e+00])

In [15]:
## Section: Comparisons, Masks, and Boolean Logic

In [14]:
# Comparison Operators as ufuncs

In [16]:
x = np.array([1, 2, 3, 4, 5])

In [17]:
x < 3  # less than

array([ True,  True, False, False, False])

In [18]:
# <, >, !=, <=, >=, == operators can be used to get boolean response

In [20]:
# eg. with 2 dim array

In [21]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [22]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])